# Default OS image is Ubuntu 12.04 LTS Precise on Travis-CI for linux
language: c

os:
  - linux

compiler:
  - gcc

env:
  - FEATURES=huge SRCDIR=vim/src
    "CONFOPT='--enable-perlinterp --enable-pythoninterp --enable-python3interp --enable-rubyinterp --enable-luainterp --enable-tclinterp --prefix=/usr'"

# sudo required to build AppImage (does apparently enable FUSE extensions)
sudo: required

branches:
  except:
    - /^v[0-9]/

addons:
  apt:
    packages:
      - autoconf
      - libperl-dev
      - python-dev
      - python3-dev
      - liblua5.1-0-dev
      - lua5.1

before_install:
    # make sure to use default 1.9.3 ruby (switching sudo on, does add different ruby versions, GRR!)
  - rvm use 1.9.3 --install --binary --fuzzy

script:
  - NPROC=$(getconf _NPROCESSORS_ONLN)
  - (cd ${SRCDIR} && ./configure --with-features=$FEATURES $CONFOPT --enable-fail-if-missing &&  make -j$NPROC )
  - ${SRCDIR}/vim --version

after_success:
  - bash -ex scripts/appimage.sh || true

deploy:
  provider: releases
  api-key:
    secure: KMER+Njo7lIQInBVGpqvBJqFCb8hxLYlOCC2jyleYzyo+cDZTXe/qNuBSXdTvAx8+WBCTyo/ZsEhsmDyR0a0C/3UxowXiKel8sOYw0STvLGg9IW9E1+gLCvkhc2M8zRSDFaPHBezsPFWxuqDkZAxzXCKfDpSk0bsRkYZHDums8aUvOAbTrp6tJpu5MaPOqOyrBcuvb2C442T94k1gEUJ/UtStZjyUN+6X3eKO9U24pwTUjPoNXOsOEFQktCRdV7w25B9OsivgNObswa27DiKjm1GGBmVXQPUmo2ft3G/GdQbdO8B0t/0DsIRTnLsCfH0jOXSx8ntrQLn6baJ1dF6wCin7Z9fb38z+MXeo/Ki8rx14j3/Jfle4WSQgOsXcuDEX2fhw18YIuNGe4ScOFrFZRgt2YSO+EFunRMpRgifA0UoPgS2u7qlQjH1N8R/StG1EumuP3zAs+jZkukDiUKS7QJ58yi/iQJsAwJUGHPHn/NjByaT+OPg6Lc8ubkxZ70kNfD75su6eM7csbS5vrSIhkNpOKpjTZWO33CKuT0ux5j4IJrLBwtwXEQINyhJCkbYXGYZzuywY3if+tDalj3Dq/8HzLVZg0XVlxBMEOmeDaff5kbfNjLk/gzhGHLhfB2lGJstU16gTiXJxmtSkcurmPcJJQVNPD1QvAYfTIwa2OY=
  file: "*.AppImage"
  file_glob: true
  skip_cleanup: true
  #  on:
  #  tags: true

# vim:set sts=2 sw=2 tw=0 et:
